@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZjY4N2E4LTZjMjEtNDkyYi05MmNiLWE3NzlmZWU5ZTliZiIsImlhdCI6MTc3MzYwOTIzNywiZXhwIjoxNzczNjEyODM3fQ.IQl2dxl7rU9Hl_ts4n5XrfzQraci-aj0OM0gyqb1-94
@characterId = fd08d602-1064-42db-8a89-e57ce9562a4b
@characterId1 = ""
@characterId2 = ""
@teamId = ""
@userId = 64f687a8-6c21-492b-92cb-a779fee9e9bf

@email = ""


### health check ###
GET http://localhost:3000/

### USER ###

### all users
GET http://localhost:3000/user/all

### user by id    
GET http://localhost:3000/user/{{userId}}

### create user
POST http://localhost:3000/user
Content-Type: application/json

{   
    "name": "Elo",
    "password": "elotest",
    "email": "elo@gmail.com"
}

### AUTH ###

### login
POST http://localhost:3000/login
Content-Type: application/json

{   
    "email": "elo@gmail.com",
    "password": "elotest"
}

### get current user
GET http://localhost:3000/user
Authorization: Bearer {{token}}

### CHARACTER ###

### create character    
POST http://localhost:3000/character
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Hugo",
    "race": "ELF",
    "role": "WARRIOR",
    "gender": "MALE",
    "customStatistics" : {
        "STRENGTH": 5,
        "HEALTH": 4,
        "MANA": 3,
        "ARMOR": 2,
        "DODGE": 1
    }
}

### get all characters
GET http://localhost:3000/character    
Authorization: Bearer {{token}}

### get character by id
GET http://localhost:3000/character/{{characterId}}
Authorization: Bearer {{token}}

### delete character
DELETE http://localhost:3000/character/{{characterId}}
Authorization: Bearer {{token}}

### add character equipments
PUT http://localhost:3000/character/{{characterId}}/equipments/add
Authorization: Bearer {{token}}
Content-Type: application/json

["SAUCEPAN", "WOODEN_SPOON", "SAUCEPAN_LID"]

### remove character equipments
PUT http://localhost:3000/character/{{characterId}}/equipments/remove
Authorization: Bearer {{token}}
Content-Type: application/json

["HEAD", "SHIELD"]

### remove all character equipments
PUT http://localhost:3000/character/{{characterId}}/equipments/removeAll
Authorization: Bearer {{token}}

### TEAM ###

### create team
POST http://localhost:3000/team
Authorization: Bearer {{token}}
Content-Type: application/json  

{
    "name": "Les Bests"
}

### get user teams
GET http://localhost:3000/team
Authorization: Bearer {{token}}

### add characters to team
PUT http://localhost:3000/team/{{teamId}}/addCharacters
Authorization: Bearer {{token}}
Content-Type: application/json  

[
    "{{characterId1}}",
    "{{characterId2}}"
]